require('options')
require('plugins')
require('keymaps')
require('theming')

require('plugins/treesitter')
require('plugins/nvim-compe')
require('plugins/nvim-tree')
require('plugins/telescope')

require('plugins/colorizer')
require('plugins/dashboard')
require('plugins/galaxyline')
require('plugins/gitsigns')
require('plugins/indentline')
require('plugins/lspkind')
require('plugins/lsp-trouble')
require('plugins/nvim-autopairs')
require('plugins/which-key')

require('lsp')
