require('options')
require('plugins')
require('keymaps')
require('theming')

require('plugins/galaxyline')
require('plugins/indentline')
require('plugins/lsp-trouble')
require('plugins/lspkind')
require('plugins/lspsaga')
require('plugins/nvim-autopairs')
require('plugins/nvim-compe')
require('plugins/nvim-toggleterm')
require('plugins/nvim-tree')
require('plugins/telescope')
require('plugins/treesitter')
require('plugins/which-key')

require('lsp')
require('lsp/tsserver')
require('lsp/json')
require('lsp/graphql')
require('lsp/html')
require('lsp/css')
require('lsp/sumneko-lua')
require('lsp/efm-langserver')
